#define PI 3.1415926536

double det(double *A, int n);
double lngamma(double x);
void starprod(double *A, int m, int n, double *B, int mp, int nq, double *C);
int round2(double x);
double bessi0(double x);
void kronint(int *X, int n1, int m1, int *Y, int n2, int m2, int *Z);
void kron(double *X, int n1, int m1, double *Y, int n2, int m2, double *Z);
int comb(int n, int k);
void matmult(double *A,int na,int ma,double *B,int nb, int mb,double *C);
void chol(double *X, int n, double *L);
void cholsl(double *Ach, double *b, int n, double *x);
double inv(double *A, int n, double *Ainv);
void printmat(double *A,int rows, int cols);
void printintmat(int *A,int rows, int cols);
void matadd(double *A, double *B, int rows, int cols, double *C);
void matsub(double *A, double *B, int rows, int cols, double *C);
void trans(double *A,int rows, int cols, double *B);
void binvec(int d, int J, int *b);
int binvecfind(int d, int J, int *b);
int modint(int x, int y);
int factorial(int n);
void modkvec(int d, int J, int k, int *b);
void modvec(int d, int J, int *k, int *b);
int findint(int *zeta,int m,int *ind);
int find(double *zeta,int m,int *ind);
int find_thresh(double *zeta, int m, double thresh, int *ind);
void insertionSort(double *numbers, int array_size, int *indices);
void insertionSort2(double *numbers, int array_size, int *indices);
void sortint(int *numbers, int array_size, int *indices);
void matmultint(int *A,int na,int ma,int *B,int nb, int mb,int *C);
void eye(int n, double *I);
void ones(int n, double *o);
void repmat(int *Y, int nrows, int ncols, int n1, int m1, int *Z);
double mod(double x,double y);
int isinvec(int z, int *v, int m);
int isin(int *zeta, int **V, int *numvalid, int j);
void diff(int *a, int *b, int numels);
int isunique(int *zeta,int j, int r);
int setdiff(int *a, int la, int *b, int lb, int *c);
int maxint(int *a, int n);
int max2int(int a, int b);
int min2int(int a, int b);
//double min(double *a, int n, int *pos);
//double max(double *a, int n, int *pos);
double max2(double a, double b);
double min2(double a, double b);
//double atan2(double y, double x);
void nchoosek(int *v, int d, int m, int *C);
void perms(int *v, int n, int *P);
int unionint(int *A, int na, int *B, int nb, int *C);
double sign(double x);
double sec(double x);
int intersect(int *x, int n, int *y, int m, int *z);
